### ISSUE TITLE
Release 0.5.9+

### ISSUE THREAD

**Issue by 130s** [ros-visualization/rqt_tf_tree#10]
There was a change recently merged #9. While that's not a big change, I'm afraid we'd forget making a new release, which results in the change remains unavailable for users who use this package via binary.

@Peter9606 Are you interested in making a release? If not let me know so that I can take this.

**Comment by Peter9606** [comment]
@130s Thanks for involing me this. I'd like to, but I'm not very familar with the process. Could you please guide me so I can do it alone next time:)

**Comment by christian-rauch** [comment]
Ping @130s @Peter9606 
Is there any news on releasing a binary version of the package that contains the TF buffer clearing feature?

**Comment by 130s** [comment]
Sorry to block this. I'll send some basic instruction to @Peter9606 later today. If s/he can figure it out or not by the end of this week I'll make a new release.

**Comment by Peter9606** [comment]
Sorry for late response. I'm on a travel and probably cannot help you @130s  this time.

**Comment by 130s** [comment]
OK! Took care of this.

I https://github.com/ros/rosdistro/pull/20151
K https://github.com/ros/rosdistro/pull/20152
L https://github.com/ros/rosdistro/pull/20153
M https://github.com/ros/rosdistro/pull/20153
