### ISSUE TITLE
Port to ROS2

### ISSUE THREAD

**Issue by marting87** [ros-visualization/rqt_tf_tree#11]
Currently **rqt_tf_tree** is not yet ported to ROS2. 

This can be done in a similar way as [rqt_graph](https://github.com/ros-visualization/rqt_graph/tree/crystal-devel).

**Comment by marting87** [comment]
For this we need tf2_ros for python to work: https://github.com/ros2/geometry2/pull/99

**Comment by dirk-thomas** [comment]
Addressed by #13.
