### ISSUE TITLE
rqt_tf_tree fails to run due to SyntaxError

### ISSUE THREAD

**Issue by ruffsl** [ros-visualization/rqt_tf_tree#16]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - binaries
- Version or commit hash:
  - ros-eloquent-rqt-tf-tree/bionic,now 1.0.1-1bionic.20200121.233350 amd64

#### Steps to reproduce issue

Launch any set of nodes that publish tfs, then attempt to run rqt_tf_tree:

```
$ ros2 run rqt_tf_tree rqt_tf_tree 
Traceback (most recent call last):
  File "/opt/ros/eloquent/lib/rqt_tf_tree/rqt_tf_tree", line 5, in <module>
    from rqt_gui.main import Main
  File "/opt/ros/eloquent/lib/python3.6/site-packages/rqt_gui/main.py", line 40, in <module>
    import rclpy
  File "/opt/ros/eloquent/lib/python3.6/site-packages/rclpy/__init__.py", line 62
    def init(*, args: List[str] = None, context: Context = None) -> None:
              ^
SyntaxError: invalid syntax
```

#### Expected behavior

Launches an rqt window with the tf visualization plugin displayed.

#### Actual behavior

Crashes at run time even before sawing a window.

**Comment by dirk-thomas** [comment]
Thanks for the report. The script seems to be run with Python 2 which doesn't support the syntax. See #17 for a fix.

**Comment by ruffsl** [comment]
After applying the patch from https://github.com/ros-visualization/rqt_tf_tree/pull/17 , I'm now encountering this error:

```
$ ros2 run rqt_tf_tree rqt_tf_tree 
qt_gui_main() found no plugin matching "rqt_tf_tree.tf_tree.RosTfTree"
try passing the option "--force-discover"
```
