### ISSUE TITLE
found no plugin matching "rqt_tf_tree.tf_tree.RosTfTree"

### ISSUE THREAD

**Issue by ruffsl** [ros-visualization/rqt_tf_tree#19]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - binaries
- Version or commit hash:
  - ros-eloquent-rqt-tf-tree/bionic,now 1.0.1-1bionic.20200121.233350 amd64

#### Steps to reproduce issue

Patch package to include https://github.com/ros-visualization/rqt_tf_tree/pull/18
Launch any set of nodes that publish tfs, then attempt to run rqt_tf_tree:

```
$ ros2 run rqt_tf_tree rqt_tf_tree 
qt_gui_main() found no plugin matching "rqt_tf_tree.tf_tree.RosTfTree"
try passing the option "--force-discover"
```

#### Expected behavior

Launches an rqt window with the tf visualization plugin displayed.

#### Actual behavior

Crashes at run time even before launching window.

Perhaps this has something to do with the fact that the tf_tree view is absent from the dropdown menu  under Plugins->Visualizations in rqt. Is there something else blocking the tf plugin's registration? 

### Melodic:

![image](https://user-images.githubusercontent.com/2293573/74116290-c8c09380-4b67-11ea-858e-46324838e780.png)

### Eloquent:

![image](https://user-images.githubusercontent.com/2293573/74116313-e42b9e80-4b67-11ea-9f82-3acb9e2fb323.png)

**Comment by dirk-thomas** [comment]
Previously posted here: https://github.com/ros-visualization/rqt_tf_tree/issues/16#issuecomment-583926635

Does `rqt --list-plugins` contain the plugin?

Have you tried the suggested option `--force-discover`?

**Comment by ruffsl** [comment]
As of writing with the most recent version sync, the following is what I'm now encountering
* ros-eloquent-rqt-tf-tree/bionic,now 1.0.2-1bionic.20200218.191417 amd64 

> Does rqt --list-plugins contain the plugin?

Yep, looks like it:

```
$ rqt --list-plugins | grep tree
rqt_tf_tree.tf_tree.RosTfTree
```

However, when opening the tf tree plugin from the dropdown menu or starting the plugin outright, it seems to wait forever for a not available service:

```
$ rqt --force-discover
service not available, waiting again...
service not available, waiting again...
service not available, waiting again...
...
```

```
$ rqt_tf_tree 
service not available, waiting again...
service not available, waiting again...
service not available, waiting again...
...
```

**Comment by dirk-thomas** [comment]
> when opening the tf tree plugin from the dropdown menu or starting the plugin outright, it seems to wait forever for a not available service:

That seems to be an entirely different issue from what this ticket is about. Maybe creating a new ticket would make more sense. It would be good to include all your steps and how / if you are running a node with the service `tf2_frames`.

**Comment by ruffsl** [comment]
Yea, I don't know when this was solved, I'll make a new issue.
Third installment of tring to use rqt_tf_tree, coming soon to a ticket near you.

**Comment by phil123456** [comment]
learning ros is EXTREMELY tedious
the amount of missing non working things is baffling to say the least
