### ISSUE TITLE
no module named rospkg

### ISSUE THREAD

**Issue by linuxsocke** [ros-visualization/rqt_tf_tree#24]
Hi, 
I have ros noetic and Ubuntu 20.04 and get the following message:
`Traceback (most recent call last):
  File "/opt/ros/noetic/lib/rqt_tf_tree/rqt_tf_tree", line 5, in <module>
    from rqt_gui.main import Main
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/main.py", line 40, in <module>
    from rospkg.rospack import RosPack
ImportError: No module named rospkg.rospack`

I have python3-rospkg installed in the dir:
`/usr/share/doc/python3-rospkg`

Am I missing something in the PATH or PYTHONPATH?

I tried to install python-rospkg via pip2 but I dont want to use python2 ..

**Comment by dirk-thomas** [comment]
Try running the script explicitly with Python 3: `python3 /opt/ros/noetic/lib/rqt_tf_tree/rqt_tf_tree`. If that works you likely just need to make sure that you have the latest version of this package since the shebang line of that script was fixed in #21 / version 0.6.2.

**Comment by Miha22** [comment]
This is an issue because Ubuntu 20.04 has dropped python and python2, and now using python 3. Install the following lib to run ROS on Ubuntu 20.04: sudo apt install python-is-python3
