### ISSUE TITLE
Release for foxy and galactic distributions

### ISSUE THREAD

**Issue by bjsowa** [ros-visualization/rqt_tf_tree#31]
Is there anything holding back this package from being released for Foxy and Galactic distributions? If not, I would appreciate if you could do this.

**Comment by mabelzhang** [comment]
Release pending approvals of these PRs
https://github.com/ros/rosdistro/pull/31213
https://github.com/ros/rosdistro/pull/31214
and respective distro syncs. [Foxy](https://discourse.ros.org/t/preparing-for-foxy-sync-2021-11-04/22945/2) and [Galactic](https://discourse.ros.org/t/preparing-for-galactic-sync-2021-11-09/22949/2) have just been synced in the past week or two, so it'll probably be a month or so before they're out.

**Comment by arne48** [comment]
@mabelzhang Can this issue be closed? 
According to the Packages file of the ROS2 Repository version 1.0.3-1 is already actively distributed for Foxy and Galactic.

**Comment by mabelzhang** [comment]
Yep. Should have closed with my last comment. Thanks!

**Comment by AndreasR30** [comment]
Is there also a release planned for ros2 humble?
