### ISSUE TITLE
ROS 2 port appears to be broken

### ISSUE THREAD

**Issue by joshnewans** [ros-visualization/rqt_tf_tree#32]
Despite the past PR #13 for the ROS 2 port, this doesn't seem to be functioning.

Apparently this was a known issue (https://github.com/ros2/geometry2/pull/198) due to the FrameGraph server not being enabled in tf2_ros, however that appears to have been merged some time ago, and this package still doesn't run for me.

It simply prints `service not available, waiting again...` continuously.
I'm not too familiar with the inner workings of the `tf2` system, I've tried running `tf2_ros tf2_monitor` and `tf2_ros buffer_server` based on some things I read but to no avail.

Does anyone have any thoughts as to what needs to be done?
Also, if this is resolved presumably we can look at pushing to foxy/galactic/rolling and closing #31 too.

**Comment by tomlogan501** [comment]
Hope this issue will be solved, I can test if you want.

**Comment by tomlogan501** [comment]
I test it today and it works, there is the line 75 too to change. I will make a PR.

**Comment by mabelzhang** [comment]
Closing with #33
