### ISSUE TITLE
fixup release for noetic missing

### ISSUE THREAD

**Issue by v4hn** [ros-visualization/rqt_tf_tree#36]
The released package for noetic is broken. The patch [was already merged](https://github.com/ros-visualization/rqt_tf_tree/pull/30), but the release to fix it for everyone is still missing. Could you please do a quick release into noetic @mabelzhang ?

**Comment by v4hn** [comment]
@arne48 Could you please take care of this? :-)

**Comment by arne48** [comment]
@v4hn New version is released :+1: 
Thank you

**Comment by v4hn** [comment]
thank you for stepping up! :medal_sports:
