### ISSUE TITLE
Add maintainer

### ISSUE THREAD

**Issue by v4hn** [ros-visualization/rqt_tf_tree#37]
@130s @mabelzhang

I created #36 over a month ago asking for a simple bloom release and got no response.

Talking to @arne48 about this [he proposed to step up as an additional maintainer for this repository](https://github.com/ros-visualization/rqt_robot_monitor/pull/35#issuecomment-1069755315).
Could you add him as maintainer here and give him access to the gbp repository?

Alternatively you could also [orphan the package](http://wiki.ros.org/OrphanedPackage) and give me access to the repo to push a version commit to release.

Either is fine by me, but I would like to resolve this soon.

**Comment by 130s** [comment]
Sorry for hiatus. I added @arne48 to @tf_tree_maintainers that has write access to this repo. Later I can try adding to GBP as well (I have to go now).

**Comment by arne48** [comment]
@130s Thank you very much. I am looking forward to help with this repo :)
BTW I am already am member of the "rqt plugin" team, which has "maintain" permissions for this repo.
I am not sure if the "tf_tree_maintainers" team with "write" permissions is necessary.
But I would definitely need permissions for the ros-gbp/rqt_tf_tree-release repo to bloom releases.

**Comment by mabelzhang** [comment]
I don't have admin right in https://github.com/ros-gbp/rqt_tf_tree-release either.
Maybe @clalancette?

**Comment by v4hn** [comment]
I don't want to spill permissions, so let's just say there are 7 admins for the gbp repo, including the usual @clalancette, @wjwwood and @tfoote . could any one of you please add @arne48 there?

**Comment by clalancette** [comment]
I've just invited @arne48 as a maintainer on https://github.com/ros-gbp/rqt_tf_tree-release
