### ISSUE TITLE
Branched new humble from noetic-devel instead of dashing-devel

### ISSUE THREAD

**Issue by arne48** [ros-visualization/rqt_tf_tree#41]
@audrow, @wjwwood, @clalancette 
I created new humble branches in all repositories I maintain from the latest ros2 branches.
Unfortunately here I made a mistake and branched from the ros1 branch.
My permissions don't allow me to delete the wrong branch now.
Could one of you please delete the humble branch for me so that I (or you) can create the humble branch correctly?
I am very sorry for the inconveniences caused by my oversight. ><

**Comment by clalancette** [comment]
I've now deleted the humble branch.  Let me know if there is anything else you need.  I'm going to close this out for now.

**Comment by arne48** [comment]
@clalancette Thank you very much for your quick help :)

**Comment by 130s** [comment]
Default branch of this repo was `noetic-devel`, which sounds like good'ol ROS1. I changed that to `humble`.

There's also `master` branch, among others. I'm not sure which one should be the "main" development branch that's suitable for a default branch.
